development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://h:p84c1635e0315343eab147140c48c268a2fbe7e1b18ec22e88dcd9e2ec479789d@ec2-3-93-100-155.compute-1.amazonaws.com:7999
  channel_prefix: Pictionary_production

# edit this file if REDIS updates!
# in your terminal, Run `heroku config:get REDIS_URL`
# Copy and replace the above URL with that one
# Figure out a way to automate this
# https://devcenter.heroku.com/articles/config-vars#accessing-config-var-values-from-code

# 10/27/20 - (Possible fix - source: https://www.nopio.com/blog/setup-rails-application-heroku/)
# Didn't work. Reverted back to actual url for now. Try again later.

# 11/19/20 - Trying to hide redis url as GitGuardian keeps sending me warnings
# (GitGuardian has detected the following Redis URI exposed within your GitHub account.)
# Installed 'figaro' gem and followed instructions per "https://medium.com/better-programming/how-to-hide-your-api-keys-c2b952bc07e6"
# Attempt failed. 
