development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_PROVIDER'] %>
  channel_prefix: Pictionary_production

# updated 10.10.2020 (Possible fix - source: https://www.nopio.com/blog/setup-rails-application-heroku/)

# edit this file if REDIS updates!
# in your terminal, Run `heroku config:get REDIS_URL`
# Copy and replace the above URL with that one
# Figure out a way to automate this
# https://devcenter.heroku.com/articles/config-vars#accessing-config-var-values-from-code